const styles = {

  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#071a07",
    color: "#c8f0c8",
    fontFamily: "'Nunito', sans-serif",
    width: "100%",
    overflowX: "hidden",
  },

  cabecalho: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "1.4rem 2.5rem",
    borderBottom: "1px solid #2a5a2a",
    backgroundColor: "#0a1f0a",
    position: "sticky",
    top: 0,
    zIndex: 100,
    gap: "0.8rem",
  },
  cabecalhoLogo: {
    fontSize: "1.2rem",
    fontWeight: "800",
    letterSpacing: "0.15em",
    color: "#7dff7d",
    textTransform: "uppercase",
  },
  cabecalhoNav: {
    display: "flex",
    gap: "0.6rem",
    justifyContent: "center",
  },
  cabecalhoBtn: {
    backgroundColor: "#0a1f0a",
    border: "1px solid #2a5a2a",
    color: "#c8f0c8",
    padding: "0.5rem 1.4rem",
    fontSize: "0.78rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    cursor: "pointer",
    transition: "all 0.18s ease",
    fontFamily: "'Nunito', sans-serif",
    borderRadius: "999px",
  },
  cabecalhoBtnAtivo: {
    backgroundColor: "#7dff7d",
    borderColor: "#7dff7d",
    color: "#071a07",
    fontWeight: "700",
  },

  rodape: {
    marginTop: "auto",
    padding: "1.5rem 2.5rem",
    borderTop: "1px solid #2a5a2a",
    backgroundColor: "#0a1f0a",
    textAlign: "center",
  },
  rodapeLink: {
    color: "#7dff7d",
    textDecoration: "none",
    fontSize: "0.8rem",
    letterSpacing: "0.1em",
    display: "block",
    marginBottom: "0.4rem",
  },
  rodapeTexto: {
    color: "#4a8a4a",
    fontSize: "0.72rem",
    letterSpacing: "0.08em",
  },

  main: {
    flex: 1,
    padding: "1.5rem",
    maxWidth: "1200px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
    overflowX: "hidden",
  },
  menu: {
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
    marginBottom: "2.5rem",
    paddingBottom: "2rem",
    borderBottom: "1px solid #2a5a2a",
    justifyContent: "center",
  },

  botao: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.6rem",
    backgroundColor: "#071a07",
    border: "1px solid #2a5a2a",
    padding: "1rem 1.2rem",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontFamily: "'Nunito', sans-serif",
    minWidth: "90px",
    flex: "1 1 80px",
    maxWidth: "130px",
    borderRadius: "20px",
    outline: "none",
    WebkitAppearance: "none",
    WebkitTapHighlightColor: "transparent",
  },
  botaoAtivo: {
    borderColor: "#7dff7d",
    backgroundColor: "#0a2a0a",
    boxShadow: "0 0 12px #7dff7d44",
  },
  botaoFoto: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    objectFit: "cover",
    border: "2px solid #3a8a3a",
    display: "block",
    margin: "0 auto",
  },
  botaoFotoPlaceholder: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    backgroundColor: "#1a4a1a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.4rem",
    border: "2px solid #3a8a3a",
    margin: "0 auto",
  },
  botaoNome: {
    fontSize: "0.72rem",
    color: "#7aaa7a",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    textAlign: "center",
  },
  botaoNomeAtivo: {
    color: "#7dff7d",
  },

  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(500px, 100%), 1fr))",
    gap: "1.5rem",
  },

  card: {
    border: "none",
    backgroundColor: "#0d220d",
    padding: "1.8rem",
    position: "relative",
    overflow: "hidden",
    borderRadius: "16px",
    boxShadow: "0 4px 24px #00000055",
    borderLeft: "4px solid #3a8a3a",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  cardTag: {
    display: "inline-block",
    fontSize: "0.65rem",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    padding: "0.3rem 0.9rem",
    marginBottom: "1rem",
    fontWeight: "800",
    borderRadius: "999px",
  },
  cardTagFacil: { backgroundColor: "#0a3d0a", color: "#4ade80", border: "1px solid #166534" },
  cardTagDificil: { backgroundColor: "#3d0a0a", color: "#f87171", border: "1px solid #991b1b" },
  cardTagAprendizado: { backgroundColor: "#0a1f3d", color: "#60a5fa", border: "1px solid #1e40af" },
  cardTagSemAprendizado: { backgroundColor: "#2a2a0a", color: "#facc15", border: "1px solid #854d0e" },

  cardTitulo: {
    fontSize: "0.85rem",
    color: "#7dff7d",
    letterSpacing: "0.1em",
    marginBottom: "0",
    textTransform: "uppercase",
    fontWeight: "700",
  },
  cardCodigo: {
    backgroundColor: "#040f04",
    border: "1px solid #1a4a1a",
    padding: "1.2rem",
    overflowX: "auto",
    fontSize: "0.72rem",
    lineHeight: "1.8",
    color: "#a8d8a8",
    fontFamily: "'Nunito', sans-serif",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    borderRadius: "12px",
    margin: "0",
    maxWidth: "100%",
  },
  cardComentario: {
    marginTop: "1rem",
    fontSize: "0.78rem",
    color: "#5a9a5a",
    fontStyle: "italic",
    lineHeight: "1.6",
    borderTop: "1px solid #1a4a1a",
    paddingTop: "0.8rem",
  },

  // novos estilos adicionados
  cardFoto: {
    width: "52px",
    height: "52px",
    borderRadius: "50%",
    objectFit: "cover",
    border: "2px solid #3a8a3a",
    flexShrink: 0,
  },
  cardSeta: {
    fontSize: "0.7rem",
    color: "#4a8a4a",
    flexShrink: 0,
  },

  conteudo: {
    maxWidth: "750px",
    margin: "0 auto",
  },
  conteudoTitulo: {
    fontSize: "0.7rem",
    letterSpacing: "0.25em",
    color: "#7dff7d",
    textTransform: "uppercase",
    marginBottom: "2.5rem",
    fontWeight: "800",
  },
  conteudoLista: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  conteudoItem: {
    display: "grid",
    gridTemplateColumns: "160px 1fr",
    gap: "1rem",
    padding: "1.2rem 1.5rem",
    borderRadius: "12px",
    backgroundColor: "#0d220d",
    boxShadow: "0 2px 12px #00000044",
    alignItems: "start",
  },
  conteudoNome: {
    fontSize: "0.8rem",
    color: "#7dff7d",
    fontWeight: "800",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    paddingTop: "0.15rem",
  },
  conteudoDescricao: {
    fontSize: "0.82rem",
    color: "#8aba8a",
    lineHeight: "1.7",
  },
};

export default styles;