const styles = {

  app: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#f4f4f2",
    color: "#2a6080",
    fontFamily: "'Syne', sans-serif",
    width: "100%",
    overflowX: "hidden",
  },

  cabecalho: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0.8rem 1.5rem",
    borderBottom: "1px solid #b0d4e8",
    backgroundColor: "#e8f4f8",
    position: "sticky",
    top: 0,
    zIndex: 100,
    gap: "0.5rem",
  },
  cabecalhoLogo: {
    fontSize: "1.2rem",
    fontWeight: "800",
    letterSpacing: "0.15em",
    color: "#1a4a60",
    textTransform: "uppercase",
  },
  cabecalhoNav: {
    display: "flex",
    gap: "0.6rem",
    justifyContent: "center",
  },
  cabecalhoBtn: {
    backgroundColor: "#e8f4f8",
    border: "2px solid #b0d4e8",
    color: "#2a6080",
    padding: "0.5rem 1.4rem",
    fontSize: "0.78rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    cursor: "pointer",
    transition: "all 0.18s ease",
    fontFamily: "'Syne', sans-serif",
    borderRadius: "999px",
  },
  cabecalhoBtnAtivo: {
    backgroundColor: "#4a9aba",
    borderColor: "#4a9aba",
    color: "#f4f4f2",
    fontWeight: "700",
  },

  rodape: {
    marginTop: "auto",
    padding: "0.8rem 1.5rem",
    borderTop: "1px solid #b0d4e8",
    backgroundColor: "#e8f4f8",
    textAlign: "center",
  },
  rodapeLink: {
    color: "#1a4a60",
    textDecoration: "underline",
    fontSize: "0.8rem",
    letterSpacing: "0.1em",
    fontWeight: "700",
    cursor: "pointer",
  },
  rodapeTexto: {
    color: "#4a9aba",
    fontSize: "0.72rem",
    letterSpacing: "0.08em",
    margin: 0,
  },

  main: {
    flex: 1,
    padding: "1.5rem",
    maxWidth: "1200px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
    overflowX: "hidden",
  },

  menu: {
    display: "flex",
    gap: "1rem",
    flexWrap: "wrap",
    marginBottom: "2.5rem",
    paddingBottom: "2rem",
    borderBottom: "1px solid #b0d4e8",
    justifyContent: "center",
  },

  botao: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.6rem",
    backgroundColor: "#e8f4f8",
    border: "2px solid #b0d4e8",
    padding: "1rem 1.2rem",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontFamily: "'Syne', sans-serif",
    minWidth: "90px",
    flex: "1 1 80px",
    maxWidth: "130px",
    borderRadius: "16px",
    outline: "none",
    WebkitAppearance: "none",
    WebkitTapHighlightColor: "transparent",
  },
  botaoAtivo: {
    borderColor: "#4a9aba",
    backgroundColor: "#c8e8f4",
    boxShadow: "0 0 12px #4a9aba33",
  },
  botaoFoto: {
    width: "64px",
    height: "64px",
    objectFit: "cover",
    border: "2px solid #b0d4e8",
    display: "block",
    margin: "0 auto",
    transition: "transform 0.2s ease",
    borderRadius: "16px",
  },
  botaoFotoPlaceholder: {
    width: "64px",
    height: "64px",
    backgroundColor: "#c8e8f4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.4rem",
    border: "2px solid #b0d4e8",
    margin: "0 auto",
    borderRadius: "16px",
  },
  botaoNome: {
    fontSize: "0.72rem",
    color: "#4a9aba",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    textAlign: "center",
  },
  botaoNomeAtivo: {
    color: "#1a4a60",
    fontWeight: "700",
  },

  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(500px, 100%), 1fr))",
    gap: "1.5rem",
  },

  card: {
    border: "none",
    backgroundColor: "#e8f4f8",
    padding: "1.8rem 2rem",
    position: "relative",
    overflow: "hidden",
    borderRadius: "16px",
    boxShadow: "0 2px 12px #4a9aba22",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  cardTag: {
    display: "inline-block",
    fontSize: "0.65rem",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    padding: "0.3rem 0.9rem",
    marginBottom: "1rem",
    fontWeight: "800",
    borderRadius: "999px",
  },
  cardTagFacil: { backgroundColor: "#fff3e0", color: "#e65100", border: "1px solid #ffb74d" },
  cardTagDificil: { backgroundColor: "#f3e5f5", color: "#7b1fa2", border: "1px solid #ce93d8" },
  cardTagAprendizado: { backgroundColor: "#e3f2fd", color: "#1565c0", border: "1px solid #90caf9" },
  cardTagSemAprendizado: { backgroundColor: "#fffde7", color: "#f9a825", border: "1px solid #ffe082" },

  cardTitulo: {
    fontSize: "0.85rem",
    color: "#1a4a60",
    letterSpacing: "0.1em",
    marginBottom: "0",
    textTransform: "uppercase",
    fontWeight: "700",
  },
  cardCodigo: {
    backgroundColor: "#c8e8f4",
    border: "none",
    padding: "1.2rem",
    overflowX: "auto",
    fontSize: "0.72rem",
    lineHeight: "1.8",
    color: "#1a4a60",
    fontFamily: "'Syne', sans-serif",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    borderRadius: "12px",
    margin: "0",
    maxWidth: "100%",
  },
  cardComentario: {
    marginTop: "1rem",
    fontSize: "0.78rem",
    color: "#4a9aba",
    fontStyle: "italic",
    lineHeight: "1.6",
    borderTop: "1px solid #b0d4e8",
    paddingTop: "0.8rem",
  },

  cardFoto: {
    width: "52px",
    height: "52px",
    borderRadius: "12px",
    objectFit: "cover",
    border: "2px solid #b0d4e8",
    flexShrink: 0,
  },
  cardSeta: {
    fontSize: "0.7rem",
    color: "#4a9aba",
    flexShrink: 0,
  },

  conteudo: {
    maxWidth: "750px",
    margin: "0 auto",
    textAlign: "center",
  },
  conteudoTitulo: {
    fontSize: "0.7rem",
    letterSpacing: "0.25em",
    color: "#1a4a60",
    textTransform: "uppercase",
    marginBottom: "2.5rem",
    fontWeight: "800",
    textAlign: "center",
  },
  conteudoLista: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  conteudoItem: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "0.5rem",
    padding: "1.2rem 1.5rem",
    borderRadius: "12px",
    backgroundColor: "#e8f4f8",
    boxShadow: "0 2px 12px #4a9aba22",
    alignItems: "start",
    textAlign: "center",
  },
  conteudoNome: {
    fontSize: "0.8rem",
    color: "#1a4a60",
    fontWeight: "800",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    paddingTop: "0.15rem",
  },
  conteudoDescricao: {
    fontSize: "0.82rem",
    color: "#4a9aba",
    lineHeight: "1.7",
  },
};

export default styles;